### ISSUE TITLE
scalaz

### ISSUE THREAD

**Issue by fommil** [syntactic-sugar-london/project-suggestions#1]
lots that a contributor can help out with. Some selfish suggestions

- https://github.com/scalaz/scalaz/issues/1662 grunt work with a huge payoff (this lets us do generic derivation of `F[_]` shaped things as per the `MonadErrorTest` example). Suitable for 7.2.
- https://github.com/scalaz/scalaz/issues/1658 for the mathematically inclined, needs to be 7.3+.

**Comment by zainab-ali** [comment]
Thanks @fommil!  scalaz/scalaz#1662 looks really useful - there are plenty of cases where I've wanted that in the past.

Would you be able to open a PR for it by copying the [template](https://github.com/syntactic-sugar-london/project-suggestions/blob/master/template.md)?

**Comment by fommil** [comment]
oh, I won't be able to be there so I guess we'd need a representative sponsor... unless you can do it?

The bigger picture of 1662 is https://gitlab.com/fommil/scalaz-deriving/issues/74 there will hopefully be an `@ideriving` or `@fderiving` annotation to generate the boilerplate. Other than the usecase of deriving a `MonadError` for a decoder (soooo useful) it would allow easy newtyping of `F[_]` things like `IO`. I want to newtype `IO` all the time to provide deterministic alternative interpreters for things like clocks and random number generators.

**Comment by zainab-ali** [comment]
Sure, I'd be happy to represent it.  I've been meaning to take a closer look at scalaz-deriving too, so it'll be interesting.

**Comment by fommil** [comment]
the really core typeclasses have been merged into 7.3. Umm, https://github.com/scalaz/scalaz/issues/1618 is great if you want to get involved in the theoretical side there.

https://github.com/scalaz/scalaz/issues/created_by/fommil is everything dangling that has bugged me while writing the book.

I just need to figure out the syntax for the generic cases and implement a few features inside iotaz.

**Comment by zainab-ali** [comment]
Some of those typeclasses are new to me - I guess I ought to read the book!
https://leanpub.com/fpmortals/read#leanpub-auto-divide-and-conquer

What do you mean by newtyping `IO`? I don't think I've come accross that pattern before.


On the subject of scalaz/scalaz#1658, it looks like the laws haven't even been added to Haskell's mtl lib yet, but are pretty much decided upon.  It would be great if we could add them there as an extension :thinking:

**Comment by fommil** [comment]
in haskell a newtype is used so that you can use different typeclass instance than the one provided for a data type, without breaking typeclass coherence. I find myself sometimes wanting to provide an alternative interpreter, e.g. `Random[IO]` for my tests, but actually doing that would break typeclass coherence (oh noes, there  are two `Random[IO]` in my system and they are doing different things!) and I'd rather create a `class MyIO[A](io: IO[A]) extends AnyVal` that has its own set of typeclasses / algebras associated with it, picking and choosing from IO.

**Comment by zainab-ali** [comment]
Ah, I see, `IO` does tend to need different interpreters for testing.  I newtype when I have multiple encoders / decoders for the same class, which boils down to the same coherence problem.

So you'd be implementing something like `GeneralizedNewtypeDeriving` in Scala?  That would be much needed!

Let me know what you think of the write up in #7.
